@startuml

abstract IKernel<T> {
    virtual & at(m, n)
    virtual size_t size_m()
    virtual size_t size_n()
}

class KernelFast<T,M,N> {
    Fastest filter processing.
    Size set at compile-time.
    ---
    {field} w : T[M][N] // weights
}

class Kernel<T> {
    Slower filter processing.
    Size set at run-time.
}

class KernelEigen<T> {
    Data structures from the Eigen
    library are used.
}

IKernel <|-- KernelFast
IKernel <|-- Kernel
IKernel <|-- KernelEigen


class global {
    convolute(IKernel&)
    convolute(KernelFast<T,M,N>&)

    load_gaussian(IKernel&)
}



@enduml
